name: Retrain Model on Dataset Change

on:
  push:
    branches:
      - main  # Adjust if your branch is different (e.g., master)
    paths:
      - 'newdata.csv'

jobs:
  retrain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.1' 

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Training Script
        run: python train_models.py  #script name

      - name: Commit Updated Models
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add models/*.pkl
          git commit -m "Auto-update .pkl files after dataset change" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
